/*
 * This file is automatically generated based on project contents and settings
 * 
 * Generated: 16.9.2025, 11:52:20
 * 
 */


#define PROJECT_ORIENTATION     LANDSCAPE

extern const uint8_t _binary_4d_gcx_start[];
extern const uint8_t _binary_4d_gcx_end[];
extern const size_t _binary_4d_gcx_size;

#define GRAPHICS_GCX _binary_4d_gcx_start


enum {
    iForm0,
    iPanelA0
};

ImageControl4D hndl;



inline void SetupMedia() {

    hndl = img.LoadImageControl(GRAPHICS_GCX);

    if (hndl == NULL) {
        gfx.Cls();
        gfx.print("Failed to initialize media\n");
        gfx.Contrast(15);
        while (true);
    }

}



