/*
 * This file is automatically generated based on project contents and settings
 * 
 * Generated: 16.10.2025, 12:06:55
 * 
 */


#define PROJECT_ORIENTATION     PORTRAIT_R

extern const uint8_t _binary_4d_gcx_start[];
extern const uint8_t _binary_4d_gcx_end[];
extern const size_t _binary_4d_gcx_size;

#define GRAPHICS_GCX _binary_4d_gcx_start


enum {
    iForm0,
    iSliderA0,
    iSliderA0Fill,
    iSliderA0Thumb,
    iGaugeB0
};

ImageControl4D hndl;



const uint16_t __in_flash() iSliderA0Info[] = {
    50
};

inline void SetupMedia() {

    hndl = img.LoadImageControl(GRAPHICS_GCX);

    if (hndl == NULL) {
        gfx.Cls();
        gfx.print("Failed to initialize media\n");
        gfx.Contrast(15);
        while (true);
    }
    img.SetProperties(hndl, iSliderA0, iSliderA0Info);

}



