# -- CONFIG
GRAPHICS4D_DIR := $(USERMOD_DIR)
MAINFILE := modexample.c
LIBFILE1 := scr/../algorithm.c

# --
SRC_USERMOD_C += $(GRAPHICS4D_DIR)/$(MAINFILE)
SRC_USERMOD_LIB_C += $(GRAPHICS4D_DIR)/$(LIBFILE1)