# -- CONFIG
GRAPHICS4D_DIR := $(USERMOD_DIR)
LIBPATH1 := scr/..

# --
SRC_USERMOD_C += $(GRAPHICS4D_DIR)/modexample.c
SRC_USERMOD_LIB_C += $(GRAPHICS4D_DIR)/$(LIBPATH1)/algorithm.c
SRC_USERMOD_CXX += $(GRAPHICS4D_DIR)/modexample.cpp
SRC_USERMOD_LIB_CXX += $(GRAPHICS4D_DIR)/$(LIBPATH1)/algorithm.cpp