#include "Graphics4D.h"
#include "GeneratedConsts.h"

/*
 *Example Programm from:
https://resources.4dsystems.com.au/manuals/workshop5/pico-sdk/
 */
int main() {

    // this is required for programming without manually entering bootloader
    stdio_init_all(); // must also enable usb stdio in CMakeLists
    // otherwise, manually put the board to bootloader mode

    gfx.Initialize();
    gfx.ScreenMode(PROJECT_ORIENTATION);
    gfx.Contrast(8);

    touch.Initialize(); // uncomment when using touch

    // Uncomment when using widgets
    SetupMedia(); // autogenerated helper function used to load graphical widgets

    // put your setup code here, to run once:
    int newval, oldval;
    uint8_t points;
    uint touched;

    img.ShowForm(hndl, iForm0);

    while (true) {
        // put your main code here, to run repeatedly:
        points = touch.GetPoints();

        if (points > 0) {
            touched = img.Touched(hndl, -1);

            if (touched == iSliderA0) {
                newval = img.GetValue(hndl, iSliderA0);        

                if (newval != oldval) {
                    img.SetValue(hndl, iGaugeB0, newval); // Update GaugeB0 value
                    img.Show(hndl, iGaugeB0); // Show iGaugeB0
                    oldval = newval;
                }
            }
        }
    }
}