// Method definitions (add these before the locals_dict)
MP_DEFINE_CONST_FUN_OBJ_1(graphics4d_initialize_obj, graphics4d_initialize);
MP_DEFINE_CONST_FUN_OBJ_1(graphics4d_cls_obj, graphics4d_cls);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_rectangle_obj, 5, 6, graphics4d_rectangle);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_rectangle_filled_obj, 5, 6, graphics4d_rectangle_filled);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_circle_obj, 4, 5, graphics4d_circle);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_line_obj, 5, 6, graphics4d_line);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_put_pixel_obj, 3, 4, graphics4d_put_pixel);
MP_DEFINE_CONST_FUN_OBJ_2(graphics4d_set_backlight_obj, graphics4d_set_backlight);
MP_DEFINE_CONST_FUN_OBJ_2(graphics4d_set_contrast_obj, graphics4d_set_contrast);
MP_DEFINE_CONST_FUN_OBJ_1(graphics4d_get_width_obj, graphics4d_get_width);
MP_DEFINE_CONST_FUN_OBJ_1(graphics4d_get_height_obj, graphics4d_get_height);
MP_DEFINE_CONST_FUN_OBJ_VAR_BETWEEN(graphics4d_load_image_control_obj, 2, 3, graphics4d_load_image_control);
MP_DEFINE_CONST_FUN_OBJ_3(graphics4d_show_image_obj, graphics4d_show_image);